---
- name: Install vault-ssh-helper
  hosts: vms
  remote_user: ansible

  tasks:
    - name: Check if vault-ssh-helper binary is present
      stat:
        path: /usr/local/bin/vault-ssh-helper
      register: ssh_helper_exists

    - name: Download vault-ssh-helper
      ansible.builtin.get_url:
        url: https://releases.hashicorp.com/vault-ssh-helper/0.2.1/vault-ssh-helper_0.2.1_linux_amd64.zip
        dest: /home/ansible/vault-ssh-helper_0.2.1_linux_amd64.zip
      when: not ssh_helper_exists.stat.exists

    - name: Unzip vault-ssh-helper
      become: True
      ansible.builtin.unarchive:
        src: /home/ansible/vault-ssh-helper_0.2.1_linux_amd64.zip
        dest: /usr/local/bin
        owner: root
        group: root
        remote_src: True
        mode: 0755
      when: not ssh_helper_exists.stat.exists

    - name: Create config directory for vault-ssh-helper
      become: True
      ansible.builtin.file:
        path: /etc/vault-ssh-helper.d
        state: directory

    - name: Copy over the vault ssh configuration template
      become: True
      template:
        src: templates/helper-config.j2
        dest: /etc/vault-ssh-helper.d/config.hcl

    - name: Check if backup of pam configuration exists
      stat:
        path: /etc/pam.d/sshd.orig
      register: pam_backup_exists

    - name: Create backup of pam configuration if it does not already exist
      become: True
      ansible.builtin.copy:
        dest: /etc/pam.d/sshd.orig
        src: /etc/pam.d/sshd
        remote_src: True
      when: not pam_backup_exists.stat.exists

    - name: Copy original pam file to the new one
      become: True
      ansible.builtin.copy:
        dest: /etc/pam.d/sshd
        src: /etc/pam.d/sshd.orig
        remote_src: True

    - name: Add ssh line in file to enable vault-ssh-helper
      become: True
      lineinfile:
        path: /etc/pam.d/sshd
        line: "auth requisite pam_exec.so quiet expose_authtok log=/var/log/vault-ssh.log /usr/local/bin/vault-ssh-helper -dev -config=/etc/vault-ssh-helper.d/config.hcl"
        insertbefore: "^@include common-auth"
        firstmatch: True

    - name: Disable common-auth
      become: True
      ansible.builtin.lineinfile:
        path: /etc/pam.d/sshd
        search_string: "@include common-auth"
        line: "#@include commmon-auth"

    - name: Add 2nd ssh line in file to enable vault-ssh-helper
      become: True
      lineinfile:
        path: /etc/pam.d/sshd
        line: "auth optional pam_unix.so not_set_pass use_first_pass nodelay"
        insertafter: "^auth requisite*"
        firstmatch: True

    - name: Check if backup of sshd_config configuration exists
      stat:
        path: /etc/ssh/sshd_config.orig
      register: sshd_backup_exists

    - name: Create backup of sshd configuration if it does not already exist
      become: True
      ansible.builtin.copy:
        dest: /etc/ssh/sshd_config.orig
        src: /etc/ssh/sshd_config
        remote_src: True
      when: not sshd_backup_exists.stat.exists

    - name: Copy original sshd_config file to the new one
      become: True
      ansible.builtin.copy:
        dest: /etc/ssh/sshd_config
        src: /etc/ssh/sshd_config.orig
        remote_src: True

    - name: Deny PasswordAuthentication
      become: True
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        search_string: "PasswordAuthentication yes"
        line: "PasswordAuthentication no"

    - name: Enable KbdInteractiveAuthentication
      become: True
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        search_string: "KbdInteractiveAuthentication no"
        line: "KbdInteractiveAuthentication yes"

    - name: Restart sshd service
      ansible.builtin.service:
        name: sshd
        state: restarted
